from Lem_sim_interface import *

hw = lemonator_sim_interface()

print(hw.pin.get())
print(hw.keypad.getc())
hw.lcd.write('test bericht')
hw.heater.set(True)
hw.heater.set(False)
hw.sirup_pump.set(True)
hw.water_pump.set(True)
print(hw.distance.read_mm())
print(hw.distance.read_mm())
print(hw.distance.read_mm())
print(hw.distance.read_mm())
print(hw.distance.read_mm())
print(hw.distance.read_mm())
hw.sirup_valve.set(True)
hw.water_valve.set(True)
print(hw.distance.read_mm())
print(hw.distance.read_mm())
hw.led_green.set(True)
hw.led_green.set(False)
hw.led_yellow.set(True)